"""
app/geo.py — the projection behind the threat map.

Everything that turns a latitude and a longitude into a position on a screen
lives here: the projection itself, the graticule, the parser for the sensor
coordinates, and the builder that assembles origins, sensors and arcs into one
model a template can render without arithmetic.

Three things are worth knowing about it.

**The projection is equirectangular**, cropped to +84°..-60° so Antarctica and
the empty polar rows do not eat half the panel. That is a deliberately plain
choice: `project()` is the only place a coordinate becomes a pixel, and the same
function generated the vendored coastline in ``templates/_world_land.svg``, so
the land and the marks cannot drift apart. If the viewBox changes here, that
file is regenerated by ``tools/build_world_svg.py`` — no second copy of these
constants exists.

**Nothing is invented.** An attacker IP the enricher could not place is not
drawn at the centre of its country or at 0,0; it is counted and reported as
unplaced. A sensor with no coordinates is listed under the map rather than
guessed at, because a honeypot map whose marks are half measurement and half
decoration is worse than no map.

**Sensor coordinates are configuration, not data.** Baseline v1.3 froze the
`nodes` table without latitude and longitude, and this dashboard does not get to
add columns to it. So a node is placed by ``DASHBOARD_NODE_COORDS``, or by its
own `nodes.location` when whoever populated that column wrote a coordinate pair
into it.
"""

from __future__ import annotations

import math
import re
from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Optional, Tuple

from app.formatting import score_band

# -- the projection --------------------------------------------------------

#: SVG user units across the full 360° of longitude.
WIDTH = 1000.0
#: Latitudes at the top and bottom edge. Antarctica is below the crop.
TOP_LAT = 84.0
BOTTOM_LAT = -60.0
#: Pixels per degree, and the height that falls out of the crop.
SCALE = WIDTH / 360.0
HEIGHT = round((TOP_LAT - BOTTOM_LAT) * SCALE, 1)

#: Meridians and parallels, in degrees.
MERIDIAN_STEP = 30
PARALLEL_STEP = 20

#: Marker radius in SVG units. The smallest is still a comfortable hit target;
#: the largest stays under a typical country.
MIN_RADIUS = 3.0
MAX_RADIUS = 13.0

#: How far an arc bows away from its chord, as a fraction of the chord length,
#: and the ceiling that keeps a half-world arc inside the panel.
ARC_BOW = 0.24
ARC_BOW_MAX = 78.0

#: A path is a strike, not a fixture: it fades in, holds, fades out, and is gone
#: for the rest of its cycle. Drawing all of them permanently is a ball of wool
#: that says only "these pairs exist"; showing each in turn says which pairs are
#: live and lets the eye follow one line at a time. The visible share of the
#: cycle is what keeps the map legible — at 200 arcs roughly thirty are lit at
#: any instant instead of all of them.
#:
#: The cycle length lives here rather than in the stylesheet because the per-arc
#: start offset is computed against it; the fade shape stays in the stylesheet,
#: as a fraction of the cycle — `.wm-arc`'s keyframes span 0% to 30% of this,
#: about 2.7s on screen. Change one and change the other.
ARC_CYCLE_SECONDS = 9.0

#: How many of the busiest arcs carry a moving tracer, riding the same cycle as
#: the line under it. All of them at once is a screensaver; the top few are a
#: read of where the pressure is.
TRACER_ARCS = 40

#: Successive multiples of the golden ratio never clump, so consecutive arcs
#: start at well-separated points of the cycle whatever the arc count — the map
#: never blinks in lockstep, and the spread does not depend on how many paths
#: happen to be drawn.
_GOLDEN_FRACTION = 0.6180339887


def project(latitude, longitude) -> Optional[Tuple[float, float]]:
    """
    ``(lat, lon)`` -> ``(x, y)`` in SVG user units, or None if unusable.

    Latitude is clamped to the crop so a Svalbard sensor lands on the top edge
    rather than off the canvas; longitude is not clamped, because a value
    outside ±180 means the record is wrong rather than extreme.
    """
    try:
        lat = float(latitude)
        lon = float(longitude)
    except (TypeError, ValueError):
        return None
    if not (-90.0 <= lat <= 90.0) or not (-180.0 <= lon <= 180.0):
        return None
    lat = max(BOTTOM_LAT, min(TOP_LAT, lat))
    return round((lon + 180.0) * SCALE, 1), round((TOP_LAT - lat) * SCALE, 1)


def graticule() -> Dict[str, List[float]]:
    """The lines of the grid, as x positions and y positions."""
    return {
        "meridians": [
            round((lon + 180.0) * SCALE, 1)
            for lon in range(-180 + MERIDIAN_STEP, 180, MERIDIAN_STEP)
        ],
        "parallels": [
            round((TOP_LAT - lat) * SCALE, 1)
            for lat in range(-40, int(TOP_LAT), PARALLEL_STEP)
        ],
        "equator": round(TOP_LAT * SCALE, 1),
    }


# -- sensor coordinates ----------------------------------------------------

_POINT = re.compile(
    r"^\s*(?P<lat>[+-]?\d+(?:\.\d+)?)\s*[,/ ]\s*(?P<lon>[+-]?\d+(?:\.\d+)?)\s*$"
)


def parse_point(text) -> Optional[Tuple[float, float]]:
    """``"24.7136, 46.6753"`` -> ``(24.7136, 46.6753)``; anything else -> None."""
    if not text:
        return None
    match = _POINT.match(str(text))
    if not match:
        return None
    lat, lon = float(match.group("lat")), float(match.group("lon"))
    if not (-90.0 <= lat <= 90.0) or not (-180.0 <= lon <= 180.0):
        return None
    return lat, lon


def parse_node_coordinates(raw) -> Dict[str, Tuple[float, float]]:
    """
    Parse ``DASHBOARD_NODE_COORDS``.

        node-01:24.7136,46.6753; node-02:52.3676,4.9041

    Separated by semicolons or newlines, ``:`` or ``=`` between the node and its
    point. An entry that does not parse is skipped rather than raised on: a typo
    in one node's coordinates should cost that one mark, not the whole screen.
    """
    coordinates: Dict[str, Tuple[float, float]] = {}
    for entry in re.split(r"[;\n]", str(raw or "")):
        entry = entry.strip()
        if not entry or entry.startswith("#"):
            continue
        node, separator, point = entry.partition(":")
        if not separator:
            node, separator, point = entry.partition("=")
        parsed = parse_point(point) if separator else None
        if parsed and node.strip():
            coordinates[node.strip()] = parsed
    return coordinates


# -- the model -------------------------------------------------------------

@dataclass
class ThreatMap:
    """Everything ``_macros.worldmap()`` draws, with no arithmetic left in it."""

    #: The canvas the marks were projected onto. Carried on the model so the
    #: macro takes one argument and cannot be handed a mismatched viewBox.
    width: float = WIDTH
    height: float = HEIGHT
    grid: Dict[str, List[float]] = field(default_factory=graticule)

    origins: List[Dict[str, Any]] = field(default_factory=list)
    sensors: List[Dict[str, Any]] = field(default_factory=list)
    arcs: List[Dict[str, Any]] = field(default_factory=list)
    #: Nodes with no coordinates — named under the map, never guessed at.
    unplaced_sensors: List[Dict[str, Any]] = field(default_factory=list)
    #: True when there were more origins than the marker cap allows. A count is
    #: deliberately not offered: the query stops at the cap, so the only honest
    #: statement available is "there are more than these".
    truncated: bool = False
    peak_events: int = 0
    total_events: int = 0

    @property
    def is_empty(self) -> bool:
        return not self.origins and not self.sensors


def _radius(events: int, peak: int) -> float:
    """Area-proportional radius: the circle, not its width, carries the count."""
    if peak <= 0 or events <= 0:
        return MIN_RADIUS
    return round(
        MIN_RADIUS + (MAX_RADIUS - MIN_RADIUS) * math.sqrt(events / float(peak)), 2
    )


def _arc(start: Tuple[float, float], end: Tuple[float, float]) -> Dict[str, Any]:
    """
    A quadratic bézier from origin to sensor, bowed away from its chord.

    When the short way between the two runs across the antimeridian the curve is
    drawn off the edge of the canvas and a mirror offset is returned with it;
    the template draws the same path twice, once shifted by a full world width,
    so the arc leaves one edge and arrives at the other instead of sweeping the
    wrong way across the whole map.
    """
    x1, y1 = start
    x2, y2 = end

    mirror = 0.0
    if abs(x2 - x1) > WIDTH / 2:
        mirror = math.copysign(WIDTH, x2 - x1)
        x2 -= mirror

    dx, dy = x2 - x1, y2 - y1
    length = math.hypot(dx, dy) or 1.0
    # Perpendicular to the chord, always the side pointing up the page, so every
    # arc on the map bows the same way and two arcs between the same pair of
    # points cannot cancel each other out into a straight line.
    nx, ny = dy / length, -dx / length
    if ny > 0:
        nx, ny = -nx, -ny

    bow = min(length * ARC_BOW, ARC_BOW_MAX)
    cx = round((x1 + x2) / 2 + nx * bow, 1)
    cy = round((y1 + y2) / 2 + ny * bow, 1)

    return {
        "d": f"M{x1} {y1} Q{cx} {cy} {round(x2, 1)} {round(y2, 1)}",
        "mirror": round(mirror, 1),
    }


def _sensor_marks(
    nodes: Iterable[Dict[str, Any]], coordinates: Dict[str, Tuple[float, float]]
) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]], Dict[str, Dict[str, Any]]]:
    """Split the fleet into placed marks and unplaced rows, keeping the index."""
    placed: List[Dict[str, Any]] = []
    unplaced: List[Dict[str, Any]] = []
    index: Dict[str, Dict[str, Any]] = {}

    for node in nodes:
        node_id = node.get("node_id")
        point = coordinates.get(node_id) or parse_point(node.get("location"))
        position = project(*point) if point else None
        if position is None:
            unplaced.append(node)
            continue
        mark = {
            "node_id": node_id,
            "x": position[0],
            "y": position[1],
            "latitude": point[0],
            "longitude": point[1],
            "health": node.get("health") or "unknown",
            "status": node.get("status"),
            "location": node.get("location") or node.get("hostname"),
            "events": 0,
            "attackers": 0,
        }
        placed.append(mark)
        index[node_id] = mark
    return placed, unplaced, index


def build(
    origins: Iterable[Dict[str, Any]],
    paths: Iterable[Dict[str, Any]] = (),
    nodes: Iterable[Dict[str, Any]] = (),
    coordinates: Dict[str, Tuple[float, float]] = None,
    max_origins: int = 150,
    max_arcs: int = 200,
) -> ThreatMap:
    """
    Assemble the map from storage rows.

    `origins` are ``Database.get_attack_origins()`` rows, `paths` are
    ``get_attack_paths()`` rows and `nodes` are the health rows the Nodes screen
    already builds. Ask the storage layer for one row more than `max_origins`
    and the extra one is what sets ``truncated``: the map then says it is
    showing the heaviest few rather than implying it is showing everything.

    Arcs are only ever drawn between two marks that are both on the map, and
    everything counted here is counted over those marks: a sensor's totals are
    what reached it *from the origins on this map*, which is the figure the arcs
    around it actually explain. `max_arcs` thins the drawing without changing
    that arithmetic.
    """
    sensors, unplaced, sensor_index = _sensor_marks(nodes, coordinates or {})

    ranked = sorted(origins, key=lambda row: row.get("events") or 0, reverse=True)
    truncated = len(ranked) > max_origins
    rows = ranked[:max_origins]

    # Both totals describe the marks on the canvas, not the query behind them,
    # so a share adds up to the map you are looking at.
    total_events = sum(row.get("events") or 0 for row in rows)
    peak = max((row.get("events") or 0 for row in rows), default=0)

    marks: List[Dict[str, Any]] = []
    positions: Dict[str, Tuple[float, float]] = {}
    for row in rows:
        position = project(row.get("latitude"), row.get("longitude"))
        if position is None:
            continue
        ip = row["attacker_ip"]
        positions[ip] = position
        events = row.get("events") or 0
        risk = row.get("risk_score")
        marks.append({
            **row,
            "x": position[0],
            "y": position[1],
            "radius": _radius(events, peak),
            "band": score_band(risk),
            "share": round(100.0 * events / total_events, 1) if total_events else 0.0,
            "breached": bool(row.get("login_successes")),
        })

    arcs: List[Dict[str, Any]] = []
    heaviest = max((row.get("events") or 0 for row in paths), default=0)
    for row in sorted(paths, key=lambda row: row.get("events") or 0, reverse=True):
        origin = positions.get(row.get("attacker_ip"))
        sensor = sensor_index.get(row.get("node_id"))
        if origin is None or sensor is None:
            continue
        sensor["events"] += row.get("events") or 0
        sensor["attackers"] += 1
        if len(arcs) >= max_arcs:
            continue
        events = row.get("events") or 0
        weight = math.sqrt(events / float(heaviest)) if heaviest else 0.0
        arcs.append({
            **_arc(origin, (sensor["x"], sensor["y"])),
            "attacker_ip": row.get("attacker_ip"),
            "node_id": row.get("node_id"),
            "events": events,
            "last_seen": row.get("last_seen"),
            # Presentation the template would otherwise have to compute: a busy
            # path is thicker and brighter than a quiet one.
            "width": round(0.5 + 1.6 * weight, 2),
            # The peak of the fade rather than a fixed opacity: a busy path is
            # brighter than a quiet one for the seconds it is on screen.
            "opacity": round(0.22 + 0.5 * weight, 2),
            "tracer": len(arcs) < TRACER_ARCS,
            # Negative delay: every path starts part-way through its own cycle,
            # so the map opens already populated instead of building up from an
            # empty panel. Derived from the index rather than randomised, so a
            # refresh does not reshuffle which paths are lit together.
            "delay": -round(
                ARC_CYCLE_SECONDS * ((len(arcs) * _GOLDEN_FRACTION) % 1.0), 2
            ),
        })

    return ThreatMap(
        origins=marks,
        sensors=sensors,
        arcs=arcs,
        unplaced_sensors=unplaced,
        truncated=truncated,
        peak_events=peak,
        total_events=total_events,
    )
